/**
 * SchemaGenerator
 *
 * Zod 스키마 및 TypeScript 타입 정의를 생성합니다.
 *
 * @module screen-generator/generators/schema-generator
 */

import type { CrudColumnDef, CrudConfig } from '../_shared/types';

/**
 * 스키마 생성 결과
 */
export interface SchemaCode {
  zodSchema: string;
  typeDefinition: string;
  schemaName: string;
}

/**
 * SchemaGenerator 클래스
 *
 * 책임:
 * - CrudColumnDef → Zod 스키마 코드 생성
 * - CrudColumnDef → TypeScript 타입 정의 생성
 */
export class SchemaGenerator {
  /**
   * Zod 스키마 파일 코드 생성
   */
  generateZodSchemaFile(
    schemaName: string,
    columns: CrudColumnDef[],
    config: CrudConfig
  ): SchemaCode {
    const pascalName = this.toPascalCase(schemaName);
    
    const zodSchema = `/**
 * ${pascalName} Schema
 *
 * @generated by AI Factory Lab
 * @created ${new Date().toISOString()}
 */

import { z } from 'zod';

/**
 * ${pascalName} Row Schema
 */
export const ${pascalName}RowSchema = z.object({
${this.generateZodFields(columns)}
});

/**
 * ${pascalName} Search Params Schema
 */
export const ${pascalName}SearchSchema = z.object({
  keyword: z.string().optional(),
  page: z.number().optional().default(1),
  pageSize: z.number().optional().default(${config.pageSize ?? 50}),
});

/**
 * ${pascalName} Save Input Schema
 */
export const ${pascalName}SaveSchema = z.object({
  inserts: z.array(${pascalName}RowSchema),
  updates: z.array(${pascalName}RowSchema),
  deletes: z.array(z.string()),
});

/**
 * Inferred Types
 */
export type ${pascalName}Row = z.infer<typeof ${pascalName}RowSchema>;
export type ${pascalName}Search = z.infer<typeof ${pascalName}SearchSchema>;
export type ${pascalName}Save = z.infer<typeof ${pascalName}SaveSchema>;
`;

    const typeDefinition = this.generateTypeDefinition(pascalName, columns);

    return {
      zodSchema,
      typeDefinition,
      schemaName: pascalName,
    };
  }

  /**
   * Zod 필드 정의 생성
   */
  private generateZodFields(columns: CrudColumnDef[]): string {
    return columns.map(col => {
      let zodType: string;
      let comment = col.headerName;

      switch (col.editorType) {
        case 'number':
          zodType = this.generateNumberZod(col);
          break;
        case 'checkbox':
          zodType = 'z.boolean()';
          break;
        case 'date':
          zodType = 'z.string().regex(/^\\d{4}-\\d{2}-\\d{2}$/, "YYYY-MM-DD 형식")';
          break;
        case 'datetime':
          zodType = 'z.string().datetime()';
          break;
        case 'select':
          zodType = this.generateSelectZod(col);
          break;
        default:
          zodType = this.generateTextZod(col);
      }

      if (!col.required) {
        zodType += '.nullable().optional()';
      }

      return `  /** ${comment} */\n  ${col.field}: ${zodType},`;
    }).join('\n\n');
  }

  /**
   * 숫자 타입 Zod 생성
   */
  private generateNumberZod(col: CrudColumnDef): string {
    const constraints: string[] = [];
    if (col.minValue !== undefined) constraints.push(`.min(${col.minValue})`);
    if (col.maxValue !== undefined) constraints.push(`.max(${col.maxValue})`);
    return `z.number()${constraints.join('')}`;
  }

  /**
   * 텍스트 타입 Zod 생성
   */
  private generateTextZod(col: CrudColumnDef): string {
    const constraints: string[] = [];
    if (col.maxLength) constraints.push(`.max(${col.maxLength})`);
    if (col.pattern) constraints.push(`.regex(/${col.pattern}/)`);
    return `z.string()${constraints.join('')}`;
  }

  /**
   * Select 타입 Zod 생성
   */
  private generateSelectZod(col: CrudColumnDef): string {
    if (Array.isArray(col.options)) {
      const values = col.options.map(opt => `'${opt.value}'`).join(', ');
      return `z.enum([${values}])`;
    }
    return 'z.string()';
  }

  /**
   * TypeScript 타입 정의 생성
   */
  private generateTypeDefinition(name: string, columns: CrudColumnDef[]): string {
    const fields = columns.map(col => {
      let tsType: string;

      switch (col.editorType) {
        case 'number':
          tsType = 'number';
          break;
        case 'checkbox':
          tsType = 'boolean';
          break;
        default:
          tsType = 'string';
      }

      const optional = col.required ? '' : '?';
      const nullable = col.required ? '' : ' | null';

      return `  /** ${col.headerName} */\n  ${col.field}${optional}: ${tsType}${nullable};`;
    }).join('\n\n');

    return `/**
 * ${name} Type Definition
 */
export interface ${name}Row {
${fields}
}
`;
  }

  /**
   * snake_case → PascalCase 변환
   */
  private toPascalCase(str: string): string {
    return str
      .toLowerCase()
      .replace(/_([a-z])/g, (_, letter: string) => letter.toUpperCase())
      .replace(/^./, s => s.toUpperCase());
  }
}

export default SchemaGenerator;
