'use client';

import { useMemo, useState, useEffect } from 'react';
import { AgGridReact } from 'ag-grid-react';
import { ModuleRegistry, AllCommunityModule } from 'ag-grid-community';
import type { ColDef, ColGroupDef, RowClassParams } from 'ag-grid-community';
import { Search, RotateCcw, Download, Loader2 } from 'lucide-react';
// 공통 옵션 컴포넌트
import {
  SiteSelect,
  YearMonthPicker,
  YearPicker,
  CustomerSelect,
  MaterialSelect,
  ModelSelect,
  AccountSelect,
  ExpenSelSelect,
  DepartmentSelect,
  SelCodeSelect,
} from "~/components/options";

// AG Grid 모듈 등록 (필수!)
ModuleRegistry.registerModules([AllCommunityModule]);

/**
 * 부서관리
 * @generated by AI Factory Lab
 */

const styles = {
  container: { display: 'flex', flexDirection: 'column' as const, height: '100%', padding: 16, backgroundColor: '#ffffff', fontFamily: 'sans-serif' },
  title: { fontSize: 18, fontWeight: 600, marginBottom: 12, color: '#161616' },
  searchContainer: { display: 'flex', alignItems: 'flex-end' as const, gap: 16, marginBottom: 12, padding: 12, backgroundColor: '#f4f4f4', border: '1px solid #e0e0e0' },
  searchField: { display: 'flex', flexDirection: 'column' as const, gap: 4 },
  label: { fontSize: 12, color: '#525252' },
  input: { height: 32, padding: '0 8px', border: '1px solid #e0e0e0', minWidth: 120 },
  buttonGroup: { display: 'flex', gap: 8, marginLeft: 'auto' },
  button: { height: 32, padding: '0 16px', border: 'none', cursor: 'pointer', fontSize: 14 },
  gridContainer: { width: '100%', flex: 1, minHeight: 300 },
};

export default function Screen000028() {
  const columnDefs = [
    {
      "headerName": "plant_site_code",
      "field": "plant_site_code",
      "width": 120,
      "editable": false
    },
    {
      "headerName": "yyyymm",
      "field": "yyyymm",
      "width": 120,
      "editable": false
    },
    {
      "headerName": "scenario_code",
      "field": "scenario_code",
      "width": 120,
      "editable": false
    },
    {
      "headerName": "department_code",
      "field": "department_code",
      "width": 120,
      "editable": false
    },
    {
      "headerName": "department_name",
      "field": "department_name",
      "width": 120,
      "editable": true
    },
    {
      "headerName": "parent_department_code",
      "field": "parent_department_code",
      "width": 120,
      "editable": true
    },
    {
      "headerName": "cost_center_mapping_code",
      "field": "cost_center_mapping_code",
      "width": 120,
      "editable": true
    },
    {
      "headerName": "is_production_dept",
      "field": "is_production_dept",
      "width": 120,
      "editable": true
    },
    {
      "headerName": "use_yn",
      "field": "use_yn",
      "width": 120,
      "editable": true
    }
  ];

  const defaultColDef = useMemo(() => ({
    sortable: true,
    resizable: true,
    filter: true,
  }), []);

  const [rowData, setRowData] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);

  const [searchYearMonth1, setSearchYearMonth1] = useState('');

  const fetchData = async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams();
      if (searchYearMonth1) params.append('searchYearMonth1', searchYearMonth1);
      const queryString = params.toString();
      const url = `/api/screens/SC_BI_DEPT_MST/data${queryString ? '?' + queryString : ''}`;
      const response = await fetch(url);
      if (!response.ok) throw new Error('Failed to fetch');
      const result = await response.json();
      setRowData(result.data || []);
    } catch (error) {
      console.error('Error:', error);
      setRowData([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  const handleSearch = () => fetchData();

  const handleReset = () => {
    setSearchYearMonth1('');
    fetchData();
  };

  return (
    <div style={styles.container}>
      <h1 style={styles.title}>부서관리</h1>

      <div style={styles.searchContainer}>
        <div key="searchYearMonth1" style={styles.searchField}>
          <label style={styles.label}>조회월</label>
          <input
            type="text"
            value={searchYearMonth1}
            onChange={(e) => setSearchYearMonth1(e.target.value)}
            style={styles.input}
            placeholder="조회월"
          />
        </div>
        <div style={styles.buttonGroup}>
          <button onClick={handleSearch} style={{ ...styles.button, backgroundColor: '#0f62fe', color: 'white' }}>
            검색
          </button>
          <button onClick={handleReset} style={{ ...styles.button, backgroundColor: '#e0e0e0', color: '#161616' }}>
            초기화
          </button>
        </div>
      </div>

      <div className="ag-theme-alpine" style={styles.gridContainer}>
        <AgGridReact
          rowData={rowData}
          columnDefs={columnDefs}
          defaultColDef={defaultColDef}
          loading={loading}
        />
      </div>
    </div>
  );
}