'use client';

import { useState, useEffect, useCallback, useRef } from 'react';
import RealGrid, { GridView, LocalDataProvider, ValueType } from 'realgrid';
import { Search, RotateCcw, Plus, Save, Trash2, Download, Loader2 } from 'lucide-react';

// 공통 옵션 컴포넌트
import {
  SiteSelect,
  YearMonthPicker,
  YearPicker,
  CustomerSelect,
  MaterialSelect,
  AccountSelect,
  DepartmentSelect,
  SelCodeSelect,
} from '~/components/options';


/**
 * 설비정보
 * @generated by AI Factory Lab (RealGrid)
 */

export default function SC_BI_EQP_MSTMasterScreen() {
  // RealGrid 참조
  const containerRef = useRef<HTMLDivElement>(null);
  const gridViewRef = useRef<GridView | null>(null);
  const dataProviderRef = useRef<LocalDataProvider | null>(null);
  
  // 상태
  const [loading, setLoading] = useState(false);
  const [modifiedRows, setModifiedRows] = useState(new Set());
  const [deletedRows, setDeletedRows] = useState<any[]>([]);
  
  const [searchYearMonth1, setSearchYearMonth1] = useState('');

  // RealGrid 필드 정의
  const fields = [
    { fieldName: "plant_site_code", dataType: ValueType.TEXT },
    { fieldName: "yyyymm", dataType: ValueType.TEXT },
    { fieldName: "scenario_code", dataType: ValueType.TEXT },
    { fieldName: "equipment_code", dataType: ValueType.TEXT },
    { fieldName: "equipment_name", dataType: ValueType.TEXT },
    { fieldName: "managed_cost_center_code", dataType: ValueType.TEXT },
    { fieldName: "manufacturer_name", dataType: ValueType.TEXT },
    { fieldName: "acquisition_date", dataType: ValueType.TEXT },
    { fieldName: "power_usage_per_hour", dataType: ValueType.NUMBER },
    { fieldName: "depreciation_cost_month", dataType: ValueType.NUMBER }
  ];

  // RealGrid 컬럼 정의
  const columns = [
  {
    "name": "plant_site_code",
    "fieldName": "plant_site_code",
    "header": {
      "text": "plant_site_code"
    },
    "width": 120,
    "editable": false,
    "styles": {
      "textAlignment": "center"
    }
  },
  {
    "name": "yyyymm",
    "fieldName": "yyyymm",
    "header": {
      "text": "yyyymm"
    },
    "width": 120,
    "editable": false,
    "styles": {
      "textAlignment": "center"
    }
  },
  {
    "name": "scenario_code",
    "fieldName": "scenario_code",
    "header": {
      "text": "scenario_code"
    },
    "width": 120,
    "editable": false,
    "styles": {
      "textAlignment": "center"
    }
  },
  {
    "name": "equipment_code",
    "fieldName": "equipment_code",
    "header": {
      "text": "equipment_code"
    },
    "width": 120,
    "editable": false,
    "styles": {
      "textAlignment": "center"
    }
  },
  {
    "name": "equipment_name",
    "fieldName": "equipment_name",
    "header": {
      "text": "equipment_name"
    },
    "width": 120,
    "editable": true,
    "styles": {
      "textAlignment": "center"
    }
  },
  {
    "name": "managed_cost_center_code",
    "fieldName": "managed_cost_center_code",
    "header": {
      "text": "managed_cost_center_code"
    },
    "width": 120,
    "editable": true,
    "styles": {
      "textAlignment": "center"
    }
  },
  {
    "name": "manufacturer_name",
    "fieldName": "manufacturer_name",
    "header": {
      "text": "manufacturer_name"
    },
    "width": 120,
    "editable": true,
    "styles": {
      "textAlignment": "center"
    }
  },
  {
    "name": "acquisition_date",
    "fieldName": "acquisition_date",
    "header": {
      "text": "acquisition_date"
    },
    "width": 120,
    "editable": true,
    "styles": {
      "textAlignment": "center"
    }
  },
  {
    "name": "power_usage_per_hour",
    "fieldName": "power_usage_per_hour",
    "header": {
      "text": "power_usage_per_hour"
    },
    "width": 120,
    "editable": true,
    "styles": {
      "textAlignment": "center"
    }
  },
  {
    "name": "depreciation_cost_month",
    "fieldName": "depreciation_cost_month",
    "header": {
      "text": "depreciation_cost_month"
    },
    "width": 120,
    "editable": true,
    "styles": {
      "textAlignment": "center"
    }
  }
];

  // RealGrid 초기화
  useEffect(() => {
    if (!containerRef.current) return;
    
    // 라이센스 설정
    const license = process.env.NEXT_PUBLIC_REALGRID_LICENSE;
    if (license) {
      RealGrid.setLicenseKey(license);
    }
    
    // DataProvider & GridView 초기화
    const dataProvider = new LocalDataProvider(false);
    const gridView = new GridView(containerRef.current);
    gridView.setDataSource(dataProvider);
    
    // 필드 & 컬럼 설정
    dataProvider.setFields(fields);
    gridView.setColumns(columns);
    
    // 그리드 옵션
    gridView.setDisplayOptions({
      columnMovable: true,
      columnResizable: true,
      rowHeight: 36,
    });
    
    gridView.setHeader({ height: 40 });
    gridView.setEditOptions({ editable: true, insertable: true, deletable: true });
    gridView.setStateBar({ visible: true });
    gridView.setCheckBar({ visible: true });
    
    // 참조 저장
    gridViewRef.current = gridView;
    dataProviderRef.current = dataProvider;
    
    // 데이터 변경 이벤트
    dataProvider.onRowStateChanged = (provider, row) => {
      setModifiedRows(prev => new Set(prev).add(row));
    };
    
    // 초기 데이터 로드
    fetchData();
    
    return () => {
      gridView.destroy();
      dataProvider.destroy();
    };
  }, []);

  // 데이터 조회
  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams();
      if (searchYearMonth1) params.append('searchYearMonth1', searchYearMonth1);
      const queryString = params.toString();
      const url = `/api/screens/sc_bi_eqp_mst/data${queryString ? '?' + queryString : ''}`;
      const response = await fetch(url);
      if (!response.ok) throw new Error('Failed to fetch');
      const result = await response.json();
      
      if (dataProviderRef.current) {
        dataProviderRef.current.setRows(result.data || []);
      }
      setModifiedRows(new Set());
      setDeletedRows(new Set());
    } catch (error) {
      console.error('Error:', error);
    } finally {
      setLoading(false);
    }
  }, [searchYearMonth1]);

  // 검색
  const handleSearch = useCallback(() => {
    fetchData();
  }, [fetchData]);

  // 초기화
  const handleReset = useCallback(() => {
    setSearchYearMonth1('');
    fetchData();
  }, [fetchData]);

  // 행 추가
  const handleAddRow = useCallback(() => {
    if (dataProviderRef.current) {
      const newRow = {
      plant_site_code: '',
      yyyymm: '',
      scenario_code: '',
      equipment_code: '',
      equipment_name: '',
      managed_cost_center_code: '',
      manufacturer_name: '',
      acquisition_date: '',
      power_usage_per_hour: '',
      depreciation_cost_month: '',        _isNew: true,
      };
      dataProviderRef.current.insertRow(0, newRow);
    }
  }, []);

  // 선택된 행 삭제
  const handleDeleteSelected = useCallback(() => {
    if (!gridViewRef.current || !dataProviderRef.current) return;
    
    const checkedRows = gridViewRef.current.getCheckedRows();
    if (checkedRows.length === 0) {
      alert('삭제할 행을 선택해주세요.');
      return;
    }
    
    if (!confirm(`선택된 ${checkedRows.length}개 행을 삭제하시겠습니까?`)) {
      return;
    }
    
    // 삭제할 행의 데이터 저장 (PK 값 포함)
    const rowsToDelete = checkedRows.map(row => dataProviderRef.current?.getJsonRow(row)).filter(Boolean);
    
    // 역순으로 삭제 (인덱스 유지)
    checkedRows.sort((a, b) => b - a).forEach(row => {
      if (dataProviderRef.current) {
        dataProviderRef.current.removeRow(row);
      }
    });
    
    setDeletedRows(prev => [...prev, ...rowsToDelete]);
  }, []);

  // 저장
  const handleSave = useCallback(async () => {
    if (!dataProviderRef.current) return;
    
    // 변경된 행들 수집
    const provider = dataProviderRef.current;
    const insertedRows = [];
    const updatedRows = [];
    
    for (let i = 0; i < provider.getRowCount(); i++) {
      const state = provider.getRowState(i);
      const values = provider.getJsonRow(i);
      
      if (state === 'created') {
        insertedRows.push(values);
      } else if (state === 'updated') {
        updatedRows.push(values);
      }
    }
    
    if (insertedRows.length === 0 && updatedRows.length === 0 && deletedRows.length === 0) {
      alert('변경된 내용이 없습니다.');
      return;
    }
    
    setLoading(true);
    try {
      const response = await fetch(`/api/screens/sc_bi_eqp_mst/data`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          inserted: insertedRows,
          updated: updatedRows,
          deleted: deletedRows,
        }),
      });
      
      const result = await response.json();
      
      if (result.success) {
        alert(`저장 완료: 추가 ${result.insertedCount}건, 수정 ${result.updatedCount}건, 삭제 ${result.deletedCount}건`);
        setDeletedRows([]);
        fetchData();
      } else {
        alert('저장 실패: ' + (result.error || '알 수 없는 오류'));
        if (result.errors?.length > 0) {
          console.error('저장 오류 상세:', result.errors);
        }
      }
    } catch (error) {
      console.error('저장 오류:', error);
      alert('저장 중 오류가 발생했습니다.');
    } finally {
      setLoading(false);
    }
  }, [deletedRows, fetchData]);

  // 엑셀 다운로드
  const handleExcelExport = useCallback(() => {
    if (gridViewRef.current) {
      gridViewRef.current.exportGrid({
        type: 'excel',
        target: 'local',
        fileName: '설비정보_export.xlsx',
      });
    }
  }, []);

  // 변경 여부 확인
  const hasChanges = modifiedRows.size > 0 || deletedRows.length > 0;

  // 인라인 스타일 정의
  const styles = {
    container: { display: 'flex', flexDirection: 'column' as const, height: '100%', padding: 16, backgroundColor: '#ffffff', fontFamily: 'sans-serif' },
    title: { fontSize: 18, fontWeight: 600, marginBottom: 12, color: '#161616' },
    searchContainer: { display: 'flex', alignItems: 'flex-end', gap: 16, marginBottom: 12, padding: 12, backgroundColor: '#f4f4f4', border: '1px solid #e0e0e0' },
    searchField: { display: 'flex', flexDirection: 'column' as const, gap: 4 },
    label: { fontSize: 12, color: '#525252' },
    input: { height: 32, padding: '0 8px', border: '1px solid #e0e0e0', minWidth: 120 },
    buttonGroup: { display: 'flex', gap: 8, marginLeft: 'auto' },
    toolbar: { display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 },
    btnPrimary: { display: 'flex', alignItems: 'center', gap: 4, height: 32, padding: '0 12px', backgroundColor: '#0f62fe', color: 'white', border: 'none', fontSize: 14, cursor: 'pointer' },
    btnSuccess: { display: 'flex', alignItems: 'center', gap: 4, height: 32, padding: '0 12px', backgroundColor: '#24a148', color: 'white', border: 'none', fontSize: 14, cursor: 'pointer' },
    btnDanger: { display: 'flex', alignItems: 'center', gap: 4, height: 32, padding: '0 12px', backgroundColor: '#da1e28', color: 'white', border: 'none', fontSize: 14, cursor: 'pointer' },
    btnSecondary: { display: 'flex', alignItems: 'center', gap: 4, height: 32, padding: '0 12px', backgroundColor: '#393939', color: 'white', border: 'none', fontSize: 14, cursor: 'pointer' },
    btnDisabled: { display: 'flex', alignItems: 'center', gap: 4, height: 32, padding: '0 12px', backgroundColor: '#c6c6c6', color: 'white', border: 'none', fontSize: 14, cursor: 'not-allowed' },
    statusBar: { display: 'flex', alignItems: 'center', gap: 16, marginBottom: 8, fontSize: 12, color: '#525252' },
    statusItem: { display: 'flex', alignItems: 'center', gap: 4 },
    gridContainer: { flex: 1, minHeight: 400 },
  };

  return (
    <div style={styles.container}>
      {/* RealGrid Corporate Style */}
      <style jsx global>{`
        .realgrid-container .rg-root {
          border: 1px solid #cbd5e1 !important;
          border-radius: 8px !important;
          overflow: hidden !important;
        }
        
        .realgrid-container .rg-header-bar {
          background: linear-gradient(180deg, #1e40af 0%, #1e3a8a 100%) !important;
        }
        
        .realgrid-container .rg-header-text {
          color: #ffffff !important;
          font-weight: 600 !important;
          font-size: 13px !important;
        }
        
        .realgrid-container .rg-data-cell {
          border-right: 1px solid #e2e8f0 !important;
          border-bottom: 1px solid #e2e8f0 !important;
          padding: 8px 12px !important;
          font-size: 13px !important;
        }
        
        .realgrid-container .rg-data-row:hover {
          background: rgba(59, 130, 246, 0.06) !important;
        }
        
        .realgrid-container .rg-state-bar {
          background: #f8fafc !important;
        }
      `}</style>

      {/* 제목 */}
      <h1 style={styles.title}>
        설비정보
      </h1>

      {/* 조회조건 */}
      <div style={styles.searchContainer}>
        <YearMonthPicker
          value={searchYearMonth1}
          onChange={setSearchYearMonth1}
          label="조회월"
        />
        <div style={styles.buttonGroup}>
          <button onClick={handleSearch} style={styles.btnPrimary}>
            검색
          </button>
          <button onClick={handleReset} style={{ ...styles.btnPrimary, backgroundColor: '#e0e0e0', color: '#161616' }}>
            초기화
          </button>
        </div>
      </div>

      {/* 툴바 */}
      <div style={styles.toolbar}>
        <button onClick={handleAddRow} style={styles.btnPrimary}>
          <Plus style={{ width: 16, height: 16 }} />
          행 추가
        </button>
        <button 
          onClick={handleSave} 
          disabled={!hasChanges}
          style={hasChanges ? styles.btnSuccess : styles.btnDisabled}
        >
          <Save style={{ width: 16, height: 16 }} />
          저장
        </button>
        <button onClick={handleDeleteSelected} style={styles.btnDanger}>
          <Trash2 style={{ width: 16, height: 16 }} />
          삭제
        </button>
        <div style={{ marginLeft: 'auto' }}>
          <button onClick={handleExcelExport} style={styles.btnSecondary}>
            <Download style={{ width: 16, height: 16 }} />
            엑셀
          </button>
        </div>
      </div>

      {/* 상태 표시 */}
      {hasChanges && (
        <div style={styles.statusBar}>
          <span style={styles.statusItem}>
            <span style={{ width: 12, height: 12, backgroundColor: '#e8f5e9', border: '1px solid #c6c6c6' }}></span>
            변경 ({modifiedRows.size})
          </span>
          <span style={styles.statusItem}>
            <span style={{ width: 12, height: 12, backgroundColor: '#ffebee', border: '1px solid #c6c6c6' }}></span>
            삭제 ({deletedRows.length})
          </span>
        </div>
      )}

      {/* RealGrid */}
      <div className="realgrid-container" style={styles.gridContainer}>
        <div 
          ref={containerRef} 
          style={{ width: '100%', height: '100%' }}
        />
      </div>
    </div>
  );
}
