/**
 * ApiGenerator
 *
 * CRUD 화면용 tRPC API 라우터 코드를 생성합니다.
 *
 * @module screen-generator/generators/api-generator
 */

import type { CrudConfig, CrudColumnDef } from '../_shared/types';

/**
 * API 생성 결과
 */
export interface ApiCode {
  routerCode: string;
  routerName: string;
  tableName: string;
  procedures: string[];
}

/**
 * ApiGenerator 클래스
 *
 * 책임:
 * - CrudConfig + CrudColumnDef → tRPC 라우터 코드 생성
 * - Zod 스키마 생성
 * - CRUD 프로시저 생성 (getAll, getById, save)
 */
export class ApiGenerator {
  /**
   * tRPC 라우터 코드 생성
   */
  generateApiRouter(
    routerName: string,
    tableName: string,
    config: CrudConfig,
    columns: CrudColumnDef[]
  ): ApiCode {
    const pkField = config.primaryKey;
    const prismaModelName = this.toPascalCase(tableName);
    const prismaFieldName = this.toCamelCase(tableName);

    const routerCode = `/**
 * ${routerName} - Auto-generated CRUD API
 *
 * @generated by AI Factory Lab
 * @table ${tableName}
 * @created ${new Date().toISOString()}
 */

import { z } from 'zod';
import { createTRPCRouter, publicProcedure } from '~/server/api/trpc';
import { db } from '~/server/db';

// ============================================================
// Zod Schemas
// ============================================================

/**
 * 검색 파라미터 스키마
 */
const searchParamsSchema = z.object({
  site: z.string().optional(),
  yyyymm: z.string().optional(),
  scenario: z.string().optional(),
  keyword: z.string().optional(),
  page: z.number().optional().default(1),
  pageSize: z.number().optional().default(${config.pageSize ?? 50}),
});

/**
 * 행 데이터 스키마
 */
const rowSchema = z.object({
${this.generateZodSchema(columns)}
});

/**
 * 저장 입력 스키마 (Insert/Update/Delete)
 */
const saveInputSchema = z.object({
  inserts: z.array(rowSchema),
  updates: z.array(rowSchema),
  deletes: z.array(z.string()),
});

// ============================================================
// Router Definition
// ============================================================

export const ${routerName}Router = createTRPCRouter({
  /**
   * 전체 조회
   */
  getAll: publicProcedure
    .input(searchParamsSchema)
    .query(async ({ input }) => {
      const { page, pageSize, keyword, ...filters } = input;
      
      const where: Record<string, unknown> = {};
      
      // 필터 조건 적용
      if (filters.site) where.plant_site_code = filters.site;
      if (filters.yyyymm) where.yyyymm = filters.yyyymm;
      if (filters.scenario) where.scenario_code = filters.scenario;
      ${config.softDelete ? "where.delete_yn = 'N';" : ''}
      
      // 페이지네이션 계산
      const skip = (page - 1) * pageSize;
      const take = pageSize;
      
      const [data, total] = await Promise.all([
        db.${prismaFieldName}.findMany({
          where,
          skip,
          take,
          orderBy: { ${config.sortColumn ?? pkField}: '${config.sortDirection ?? 'asc'}' },
        }),
        db.${prismaFieldName}.count({ where }),
      ]);
      
      return {
        data,
        pagination: {
          page,
          pageSize,
          total,
          totalPages: Math.ceil(total / pageSize),
        },
      };
    }),

  /**
   * 단건 조회
   */
  getById: publicProcedure
    .input(z.string())
    .query(async ({ input }) => {
      const result = await db.${prismaFieldName}.findUnique({
        where: { ${pkField}: input },
      });
      return result;
    }),

  /**
   * 일괄 저장 (Insert/Update/Delete)
   */
  save: publicProcedure
    .input(saveInputSchema)
    .mutation(async ({ input }) => {
      const { inserts, updates, deletes } = input;
      
      const result = await db.$transaction(async (tx) => {
        let insertedCount = 0;
        let updatedCount = 0;
        let deletedCount = 0;
        
        // Insert
        if (inserts.length > 0) {
          await tx.${prismaFieldName}.createMany({
            data: inserts.map(row => ({
              ...row,
              ${config.auditColumns ? `created_at: new Date(),
              updated_at: new Date(),` : ''}
            })),
          });
          insertedCount = inserts.length;
        }
        
        // Update
        for (const row of updates) {
          await tx.${prismaFieldName}.update({
            where: { ${pkField}: (row as Record<string, unknown>).${pkField} as string },
            data: {
              ...row,
              ${config.auditColumns ? `updated_at: new Date(),` : ''}
            },
          });
        }
        updatedCount = updates.length;
        
        // Delete
        if (deletes.length > 0) {
          ${this.generateDeleteLogic(config, prismaFieldName, pkField)}
          deletedCount = deletes.length;
        }
        
        return { insertedCount, updatedCount, deletedCount };
      });
      
      return {
        success: true,
        ...result,
      };
    }),
});

export type ${this.toPascalCase(routerName)}Router = typeof ${routerName}Router;
`;

    return {
      routerCode,
      routerName,
      tableName,
      procedures: ['getAll', 'getById', 'save'],
    };
  }

  /**
   * Zod 스키마 생성 (컬럼 정의 기반)
   */
  private generateZodSchema(columns: CrudColumnDef[]): string {
    return columns.map(col => {
      let zodType: string;

      switch (col.editorType) {
        case 'number':
          zodType = 'z.number()';
          break;
        case 'checkbox':
          zodType = 'z.boolean()';
          break;
        case 'date':
        case 'datetime':
          zodType = 'z.string()'; // ISO 형식 문자열
          break;
        default:
          zodType = 'z.string()';
      }

      // 최대 길이 제한
      if (col.maxLength && col.editorType === 'text') {
        zodType = `z.string().max(${col.maxLength})`;
      }

      // 숫자 범위 제한
      if (col.editorType === 'number') {
        const constraints: string[] = [];
        if (col.minValue !== undefined) constraints.push(`.min(${col.minValue})`);
        if (col.maxValue !== undefined) constraints.push(`.max(${col.maxValue})`);
        if (constraints.length > 0) {
          zodType = `z.number()${constraints.join('')}`;
        }
      }

      // 필수 여부
      if (!col.required) {
        zodType += '.nullable().optional()';
      }

      return `  ${col.field}: ${zodType},`;
    }).join('\n');
  }

  /**
   * 삭제 로직 생성 (Soft Delete vs Hard Delete)
   */
  private generateDeleteLogic(
    config: CrudConfig,
    prismaFieldName: string,
    pkField: string
  ): string {
    if (config.softDelete) {
      return `await tx.${prismaFieldName}.updateMany({
            where: { ${pkField}: { in: deletes } },
            data: { 
              delete_yn: 'Y',
              ${config.auditColumns ? `updated_at: new Date(),` : ''}
            },
          });`;
    } else {
      return `await tx.${prismaFieldName}.deleteMany({
            where: { ${pkField}: { in: deletes } },
          });`;
    }
  }

  /**
   * snake_case → camelCase 변환
   */
  private toCamelCase(str: string): string {
    return str
      .toLowerCase()
      .replace(/_([a-z])/g, (_, letter: string) => letter.toUpperCase());
  }

  /**
   * snake_case → PascalCase 변환
   */
  private toPascalCase(str: string): string {
    const camel = this.toCamelCase(str);
    return camel.charAt(0).toUpperCase() + camel.slice(1);
  }
}

export default ApiGenerator;
