/**
 * ComponentGenerator
 *
 * ScreenSchema로부터 React 컴포넌트 코드를 생성합니다.
 * Production 모드와 Preview(Sandpack) 모드를 모두 지원합니다.
 *
 * @module screen-generator/generators/component-generator
 */

import type { ScreenSchema } from '~/features/screen-generator/types/block-schema';

/**
 * 컴포넌트 생성 결과
 */
export interface ComponentCode {
  code: string;
  mode: 'production' | 'preview';
}

/**
 * ComponentGenerator 클래스
 *
 * 책임:
 * - ScreenSchema → React 컴포넌트 코드 변환
 * - Production 모드: 실제 BlockRenderer 사용
 * - Preview 모드: Sandpack용 인라인 렌더러 사용
 */
export class ComponentGenerator {
  /**
   * Production용 컴포넌트 코드 생성
   * 실제 BlockRenderer를 import하여 사용
   */
  generateProductionComponent(
    schema: ScreenSchema,
    componentName: string
  ): string {
    const schemaCode = JSON.stringify(schema, null, 2);

    return `'use client';

import { ScreenRenderer } from '~/features/screen-generator/engine/BlockRenderer';
import type { ScreenSchema } from '~/features/screen-generator/types/block-schema';

/**
 * ${schema.screenName}
 *
 * @generated by AI Factory Lab - Block-based Architecture
 * @version ${schema.metadata?.version ?? '1.0'}
 * @created ${schema.metadata?.createdAt ?? new Date().toISOString()}
 */

const schema: ScreenSchema = ${schemaCode};

export default function ${componentName}() {
  return <ScreenRenderer schema={schema} />;
}
`;
  }

  /**
   * Preview(Sandpack)용 컴포넌트 코드 생성
   * 인라인 렌더러 포함 (외부 의존성 없음)
   */
  generatePreviewComponent(
    schema: ScreenSchema,
    componentName: string
  ): string {
    const schemaCode = JSON.stringify(schema, null, 2);
    const inlineRenderer = this.generateInlineRenderer();

    return `'use client';

import React from 'react';

/**
 * ${schema.screenName} (Preview Mode)
 *
 * @generated by AI Factory Lab - Block-based Architecture
 * @version ${schema.metadata?.version ?? '1.0'}
 * @created ${schema.metadata?.createdAt ?? new Date().toISOString()}
 */

${inlineRenderer}

// ============================================================
// ScreenSchema 정의
// ============================================================

const schema = ${schemaCode};

// ============================================================
// 메인 컴포넌트
// ============================================================

export default function ${componentName}() {
  return <ScreenRenderer schema={schema} />;
}
`;
  }

  /**
   * 모드에 따라 적절한 컴포넌트 코드 생성
   */
  generate(
    schema: ScreenSchema,
    componentName: string,
    mode: 'production' | 'preview' = 'preview'
  ): ComponentCode {
    const code = mode === 'production'
      ? this.generateProductionComponent(schema, componentName)
      : this.generatePreviewComponent(schema, componentName);

    return { code, mode };
  }

  /**
   * Sandpack 미리보기용 인라인 렌더러 생성
   * 외부 의존성 없이 동작하는 간단한 렌더러
   */
  private generateInlineRenderer(): string {
    return `// ============================================================
// Inline BlockRenderer (Sandpack 미리보기용)
// ============================================================

/**
 * 간단한 블록 렌더러 (미리보기용)
 * 실제 프로젝트에서는 ~/features/screen-generator/engine/BlockRenderer 사용
 */
function BlockRenderer({ block }) {
  if (block.visible === false) return null;

  const baseClass = "border-2 rounded-lg p-4 mb-4";

  switch (block.type) {
    case 'PAGE_HEADER':
      return (
        <div className={\`\${baseClass} border-blue-300 bg-blue-50\`}>
          <h1 className="text-2xl font-bold text-blue-900">{block.title}</h1>
          {block.description && (
            <p className="text-blue-700 mt-2">{block.description}</p>
          )}
          {block.breadcrumbs && (
            <div className="text-sm text-blue-600 mt-2">
              {block.breadcrumbs.map((b) => b.label).join(' > ')}
            </div>
          )}
        </div>
      );

    case 'SEARCH_FORM':
      return (
        <div className={\`\${baseClass} border-green-300 bg-green-50\`}>
          <h3 className="text-lg font-semibold text-green-900 mb-3">
            🔍 검색 폼
          </h3>
          <div className="flex flex-wrap gap-2">
            {block.fields?.map((field) => (
              <div key={field.name} className="px-2 py-1 bg-green-100 rounded text-xs">
                {field.label} ({field.type})
                {field.required && <span className="text-red-600"> *</span>}
              </div>
            ))}
          </div>
          <div className="mt-3 flex gap-2">
            <button className="px-3 py-1 bg-green-600 text-white rounded text-sm">
              {block.searchButtonLabel || '검색'}
            </button>
            {block.showResetButton && (
              <button className="px-3 py-1 bg-gray-400 text-white rounded text-sm">
                {block.resetButtonLabel || '초기화'}
              </button>
            )}
          </div>
        </div>
      );

    case 'TOOLBAR':
      return (
        <div className={\`\${baseClass} border-gray-300 bg-gray-50\`}>
          <div className="flex gap-2">
            {block.buttons?.map((btn) => (
              <button
                key={btn.id}
                className={\`px-3 py-1.5 rounded text-sm \${
                  btn.variant === 'primary' ? 'bg-blue-600 text-white' :
                  btn.variant === 'success' ? 'bg-green-600 text-white' :
                  btn.variant === 'danger' ? 'bg-red-600 text-white' :
                  'bg-gray-600 text-white'
                }\`}
              >
                {btn.label}
              </button>
            ))}
          </div>
        </div>
      );

    case 'DATA_GRID':
      return (
        <div className={\`\${baseClass} border-purple-300 bg-purple-50\`}>
          <h3 className="text-lg font-semibold text-purple-900 mb-3">
            📊 데이터 그리드
          </h3>
          <div className="text-sm text-purple-700 space-y-1">
            <div>컬럼 개수: {block.columns?.length || 0}개</div>
            <div>API: {block.apiEndpoint}</div>
          </div>
          <div className="mt-3 bg-purple-100 p-2 rounded">
            <div className="grid grid-cols-4 gap-2 font-semibold text-xs">
              {block.columns?.slice(0, 4).map((col) => (
                <div key={col.field}>{col.headerName}</div>
              ))}
            </div>
            <div className="text-center text-purple-400 mt-2">
              [데이터 로드 대기 중...]
            </div>
          </div>
        </div>
      );

    case 'KPI_WIDGET':
      return (
        <div className={\`\${baseClass} border-blue-300 bg-blue-50\`}>
          <h4 className="text-sm font-medium">{block.title}</h4>
          <div className="text-3xl font-bold mt-1">
            {block.value}
            {block.unit && <span className="text-lg ml-1">{block.unit}</span>}
          </div>
        </div>
      );

    case 'CHART_WIDGET':
      return (
        <div className={\`\${baseClass} border-orange-300 bg-orange-50\`}>
          <h3 className="text-lg font-semibold text-orange-900 mb-3">
            {block.title}
          </h3>
          <div
            className="bg-orange-100 rounded flex items-center justify-center text-orange-400"
            style={{ height: \`\${block.height || 300}px\` }}
          >
            📈 [{block.chartType} 차트]
          </div>
        </div>
      );

    case 'TAB_CONTAINER':
      return (
        <div className={\`\${baseClass} border-indigo-300 bg-indigo-50\`}>
          <div className="text-sm text-indigo-700 mb-3">
            탭 개수: {block.tabs?.length || 0}개
          </div>
          {block.tabs?.map((tab) => (
            <div key={tab.id} className="mb-2">
              <div className="font-semibold">{tab.label}</div>
              <div className="text-xs">블록 {tab.blocks?.length || 0}개</div>
            </div>
          ))}
        </div>
      );

    case 'CUSTOM':
      return (
        <div className={\`\${baseClass} border-pink-300 bg-pink-50\`}>
          <h3 className="text-lg font-semibold text-pink-900">
            🎨 {block.componentName}
          </h3>
        </div>
      );

    default:
      return (
        <div className={\`\${baseClass} border-red-500 bg-red-50\`}>
          <h3 className="text-lg font-semibold text-red-900">
            ⚠️ 알 수 없는 블록: {block.type}
          </h3>
        </div>
      );
  }
}

/**
 * 화면 렌더러 (미리보기용)
 */
function ScreenRenderer({ schema }) {
  const sortedBlocks = [...(schema.blocks || [])].sort((a, b) => a.order - b.order);

  return (
    <div className="p-4 bg-white">
      {sortedBlocks.map((block) => (
        <BlockRenderer key={block.id} block={block} />
      ))}
    </div>
  );
}`;
  }
}

export default ComponentGenerator;
