'use client';

import { useMemo, useState, useEffect } from 'react';
import { AgGridReact } from 'ag-grid-react';
import { ModuleRegistry, AllCommunityModule } from 'ag-grid-community';
import type { ColDef, ColGroupDef, RowClassParams } from 'ag-grid-community';
import { Search, RotateCcw, Download, Loader2 } from 'lucide-react';
// 공통 옵션 컴포넌트
import {
  SiteSelect,
  YearMonthPicker,
  YearPicker,
  CustomerSelect,
  MaterialSelect,
  ModelSelect,
  AccountSelect,
  ExpenSelSelect,
  DepartmentSelect,
  SelCodeSelect,
} from "~/components/options";

// AG Grid 모듈 등록 (필수!)
ModuleRegistry.registerModules([AllCommunityModule]);

/**
 * 부서관리
 * @generated by AI Factory Lab
 */

export default function Screen000033() {
  const gridRef = useRef(null);
  
  // 그리드 데이터
  const [rowData, setRowData] = useState([]);
  const [loading, setLoading] = useState(false);
  
  // 변경 추적 상태
  const [modifiedRows, setModifiedRows] = useState(new Set());
  const [deletedRows, setDeletedRows] = useState(new Set());
  
  const [searchYearMonth1, setSearchYearMonth1] = useState('');

  // 컬럼 정의
  const columnDefs = useMemo(() => [
  {
    "headerCheckboxSelection": true,
    "checkboxSelection": true,
    "width": 50,
    "pinned": "left",
    "lockPosition": true
  },
  {
    "headerName": "plant_site_code",
    "field": "plant_site_code",
    "width": 120,
    "editable": false,
    cellStyle: (params) => params.data?._isNew ? { backgroundColor: '#e8f5e9' } : params.data?._isModified ? { backgroundColor: '#fff3e0' } : null
  },
  {
    "headerName": "yyyymm",
    "field": "yyyymm",
    "width": 120,
    "editable": false,
    cellStyle: (params) => params.data?._isNew ? { backgroundColor: '#e8f5e9' } : params.data?._isModified ? { backgroundColor: '#fff3e0' } : null
  },
  {
    "headerName": "scenario_code",
    "field": "scenario_code",
    "width": 120,
    "editable": false,
    cellStyle: (params) => params.data?._isNew ? { backgroundColor: '#e8f5e9' } : params.data?._isModified ? { backgroundColor: '#fff3e0' } : null
  },
  {
    "headerName": "department_code",
    "field": "department_code",
    "width": 120,
    "editable": false,
    cellStyle: (params) => params.data?._isNew ? { backgroundColor: '#e8f5e9' } : params.data?._isModified ? { backgroundColor: '#fff3e0' } : null
  },
  {
    "headerName": "department_name",
    "field": "department_name",
    "width": 120,
    "editable": true,
    cellStyle: (params) => params.data?._isNew ? { backgroundColor: '#e8f5e9' } : params.data?._isModified ? { backgroundColor: '#fff3e0' } : null
  },
  {
    "headerName": "parent_department_code",
    "field": "parent_department_code",
    "width": 120,
    "editable": true,
    cellStyle: (params) => params.data?._isNew ? { backgroundColor: '#e8f5e9' } : params.data?._isModified ? { backgroundColor: '#fff3e0' } : null
  },
  {
    "headerName": "cost_center_mapping_code",
    "field": "cost_center_mapping_code",
    "width": 120,
    "editable": true,
    cellStyle: (params) => params.data?._isNew ? { backgroundColor: '#e8f5e9' } : params.data?._isModified ? { backgroundColor: '#fff3e0' } : null
  },
  {
    "headerName": "is_production_dept",
    "field": "is_production_dept",
    "width": 120,
    "editable": true,
    cellStyle: (params) => params.data?._isNew ? { backgroundColor: '#e8f5e9' } : params.data?._isModified ? { backgroundColor: '#fff3e0' } : null
  },
  {
    "headerName": "use_yn",
    "field": "use_yn",
    "width": 120,
    "editable": true,
    cellStyle: (params) => params.data?._isNew ? { backgroundColor: '#e8f5e9' } : params.data?._isModified ? { backgroundColor: '#fff3e0' } : null
  }
], []);

  // 기본 컬럼 설정
  const defaultColDef = useMemo(() => ({
    sortable: true,
    resizable: true,
    filter: true,
  }), []);

  // 데이터 조회
  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams();
      if (searchYearMonth1) params.append('searchYearMonth1', searchYearMonth1);
      const queryString = params.toString();
      const url = `/ api / screens / SC_BI_DEPT_MST/data${queryString ? '?' + queryString : ''}`;
      const response = await fetch(url);
      if (!response.ok) throw new Error('Failed to fetch');
      const result = await response.json();
      setRowData(result.data || []);
      setModifiedRows(new Set());
      setDeletedRows(new Set());
    } catch (error) {
      console.error('Error:', error);
      setRowData([]);
    } finally {
      setLoading(false);
    }
  }, [searchYearMonth1]);

  useEffect(() => {
    fetchData();
  }, []);

  // 검색
  const handleSearch = useCallback(() => {
    fetchData();
  }, [fetchData]);

  // 초기화
  const handleReset = useCallback(() => {
    setSearchYearMonth1('');
    fetchData();
  }, [fetchData]);

  // 셀 값 변경 시
  const onCellValueChanged = useCallback((event) => {
    const { data } = event;
    if (!data._isNew) {
      data._isModified = true;
    }
    setModifiedRows(prev => new Set(prev).add(data.id));
    if (event.node) {
      event.api.refreshCells({ rowNodes: [event.node], force: true });
    }
  }, []);

  // 행 추가
  const handleAddRow = useCallback(() => {
    const newRow = {
      plant_site_code: '',
      yyyymm: '',
      scenario_code: '',
      department_code: '',
      department_name: '',
      parent_department_code: '',
      cost_center_mapping_code: '',
      is_production_dept: '',
      use_yn: '',
      _isNew: true,
      id: `NEW_${Date.now()}`,
    };
    setRowData(prev => [newRow, ...prev]);
  }, []);

  // 선택된 행 삭제
  const handleDeleteSelected = useCallback(() => {
    const selectedNodes = gridRef.current?.api.getSelectedNodes();
    if (!selectedNodes || selectedNodes.length === 0) {
      alert('삭제할 행을 선택해주세요.');
      return;
    }

    if (!confirm(`선택된 ${selectedNodes.length}개 행을 삭제하시겠습니까?`)) {
      return;
    }

    const deleteIds = new Set();
    selectedNodes.forEach((node) => {
      if (!node.data._isNew) {
        deleteIds.add(node.data.id);
      }
    });

    // 새 행은 바로 제거, 기존 행은 삭제 표시
    setRowData(prev => prev.filter(row => {
      const isSelected = selectedNodes.some((n) => n.data.id === row.id);
      if (isSelected && row._isNew) return false;
      return true;
    }));

    setDeletedRows(prev => new Set([...prev, ...deleteIds]));
  }, []);

  // 저장
  const handleSave = useCallback(async () => {
    const rowsToSave = rowData.filter(row => row._isNew || row._isModified);
    const rowsToDelete = Array.from(deletedRows);

    if (rowsToSave.length === 0 && rowsToDelete.length === 0) {
      alert('변경된 내용이 없습니다.');
      return;
    }

    try {
      // TODO: API 호출 구현
      // const response = await fetch('/ api / screens / SC_BI_DEPT_MST/data', {
      //   method: 'POST',
      //   headers: { 'Content-Type': 'application/json' },
      //   body: JSON.stringify({
      //     inserts: rowsToSave.filter(r => r._isNew),
      //     updates: rowsToSave.filter(r => r._isModified && !r._isNew),
      //     deletes: rowsToDelete,
      //   }),
      // });
      
      alert(`저장 완료: 추가 ${rowsToSave.filter(r => r._isNew).length}건, 수정 ${rowsToSave.filter(r => r._isModified && !r._isNew).length}건, 삭제 ${rowsToDelete.length}건`);
      fetchData();
    } catch (error) {
      console.error('저장 오류:', error);
      alert('저장 중 오류가 발생했습니다.');
    }
  }, [rowData, deletedRows, fetchData]);

  // 엑셀 다운로드
  const handleExcelExport = useCallback(() => {
    gridRef.current?.api.exportDataAsCsv({
      fileName: '부서관리_export.csv',
    });
  }, []);

  // 변경 여부 확인
  const hasChanges = modifiedRows.size > 0 || deletedRows.size > 0 || rowData.some(r => r._isNew);

  // 인라인 스타일 정의 (Sandpack에서 Tailwind 미지원)
  const styles = {
    container: { display: 'flex', flexDirection: 'column', height: '100%', padding: 16, backgroundColor: '#ffffff', fontFamily: 'sans-serif' },
    title: { fontSize: 18, fontWeight: 600, marginBottom: 12, color: '#161616' },
    searchContainer: { display: 'flex', alignItems: 'flex-end', gap: 16, marginBottom: 12, padding: 12, backgroundColor: '#f4f4f4', border: '1px solid #e0e0e0' },
    searchField: { display: 'flex', flexDirection: 'column', gap: 4 },
    label: { fontSize: 12, color: '#525252' },
    input: { height: 32, padding: '0 8px', border: '1px solid #e0e0e0', minWidth: 120 },
    buttonGroup: { display: 'flex', gap: 8, marginLeft: 'auto' },
    toolbar: { display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 },
    btnPrimary: { display: 'flex', alignItems: 'center', gap: 4, height: 32, padding: '0 12px', backgroundColor: '#0f62fe', color: 'white', border: 'none', fontSize: 14, cursor: 'pointer' },
    btnSuccess: { display: 'flex', alignItems: 'center', gap: 4, height: 32, padding: '0 12px', backgroundColor: '#24a148', color: 'white', border: 'none', fontSize: 14, cursor: 'pointer' },
    btnDanger: { display: 'flex', alignItems: 'center', gap: 4, height: 32, padding: '0 12px', backgroundColor: '#da1e28', color: 'white', border: 'none', fontSize: 14, cursor: 'pointer' },
    btnSecondary: { display: 'flex', alignItems: 'center', gap: 4, height: 32, padding: '0 12px', backgroundColor: '#393939', color: 'white', border: 'none', fontSize: 14, cursor: 'pointer' },
    btnDisabled: { display: 'flex', alignItems: 'center', gap: 4, height: 32, padding: '0 12px', backgroundColor: '#c6c6c6', color: 'white', border: 'none', fontSize: 14, cursor: 'not-allowed' },
    statusBar: { display: 'flex', alignItems: 'center', gap: 16, marginBottom: 8, fontSize: 12, color: '#525252' },
    statusItem: { display: 'flex', alignItems: 'center', gap: 4 },
    statusNew: { width: 12, height: 12, backgroundColor: '#e8f5e9', border: '1px solid #c6c6c6' },
    statusModified: { width: 12, height: 12, backgroundColor: '#fff3e0', border: '1px solid #c6c6c6' },
    statusDeleted: { width: 12, height: 12, backgroundColor: '#ffebee', border: '1px solid #c6c6c6' },
    gridContainer: { flex: 1, minHeight: 400 },
  };

  return (
    <div style={styles.container}>
      {/* 제목 */}
      <h1 style={styles.title}>
        부서관리
      </h1>

      {/* 조회조건 */}
      <div style={styles.searchContainer}>
        <div key="searchYearMonth1" style={styles.searchField}>
            <label style={styles.label}>조회월</label>
            <input
              type="text"
              value={searchYearMonth1}
              onChange={(e) => setSearchYearMonth1(e.target.value)}
              style={styles.input}
              placeholder="조회월"
            />
          </div>
        <div style={styles.buttonGroup}>
          <button
            onClick={handleSearch}
            style={styles.btnPrimary}
          >
            검색
          </button>
          <button
            onClick={handleReset}
            style={{ ...styles.btnPrimary, backgroundColor: '#e0e0e0', color: '#161616' }}
          >
            초기화
          </button>
        </div>
      </div>

      {/* 툴바 */}
      <div style={styles.toolbar}>
        <button onClick={handleAddRow} style={styles.btnPrimary}>
          <Plus style={{ width: 16, height: 16 }} />
          행 추가
        </button>
        <button 
          onClick={handleSave} 
          disabled={!hasChanges}
          style={hasChanges ? styles.btnSuccess : styles.btnDisabled}
        >
          <Save style={{ width: 16, height: 16 }} />
          저장
        </button>
        <button onClick={handleDeleteSelected} style={styles.btnDanger}>
          <Trash2 style={{ width: 16, height: 16 }} />
          삭제
        </button>
        <div style={{ marginLeft: 'auto' }}>
          <button onClick={handleExcelExport} style={styles.btnSecondary}>
            <Download style={{ width: 16, height: 16 }} />
            엑셀
          </button>
        </div>
      </div>

      {/* 상태 표시 */}
      {hasChanges && (
        <div style={styles.statusBar}>
          <span style={styles.statusItem}>
            <span style={styles.statusNew}></span>
            신규 ({rowData.filter(r => r._isNew).length})
          </span>
          <span style={styles.statusItem}>
            <span style={styles.statusModified}></span>
            수정 ({modifiedRows.size})
          </span>
          <span style={styles.statusItem}>
            <span style={styles.statusDeleted}></span>
            삭제 ({deletedRows.size})
          </span>
        </div>
      )}

      {/* AG Grid */}
      <div className="ag-theme-alpine" style={styles.gridContainer}>
        <AgGridReact
          ref={gridRef}
          rowData={rowData}
          columnDefs={columnDefs}
          defaultColDef={defaultColDef}
          rowSelection="multiple"
          suppressRowClickSelection={true}
          onCellValueChanged={onCellValueChanged}
          getRowId={(params) => params.data.id}
          loading={loading}
          overlayLoadingTemplate="<span>데이터 로딩 중...</span>"
          overlayNoRowsTemplate="<span>조회된 데이터가 없습니다</span>"
        />
      </div>
    </div>
  );
}